
import '../App.css';

import { makeStyles } from '@material-ui/core/styles';

import {
  Link
} from "react-router-dom";

import { Button, Container, Paper, Card, CardContent, Typography } from '@material-ui/core';
import { QRCode } from 'react-qrcode-logo';

const useStyles = makeStyles({
  root: {
    minWidth: 275,
  },
  bullet: {
    display: 'inline-block',
    margin: '0 2px',
    transform: 'scale(0.8)',
  },
  title: {
    fontSize: 18,
    fontweight: 'bold',
  },
  pos: {
    marginBottom: 12,
  },
});

export default function () {

  const classes = useStyles();
  const bull = <span className={classes.bullet}>•</span>;

  return (
    <Container>

      <br/>
      <Paper elevation={3}>

      <Card className={classes.root}>
        <CardContent>
          <Typography className={classes.title} color="textPrimary">
            Android Download
        </Typography>
          <Typography variant="body2" component="p" color="textSecondary">
            The n.M app has been automatically built on github and pushed to github pages as an downloadable apk.
            The QR is been automatically generated by a react component from react-qrcode-logo. 
          <br />
          <br />
          </Typography>
          <QRCode value="https://paetzold.github.io/newmobility/app-release.apk"/>
        </CardContent>
      </Card>

      </Paper>

    </Container>
  );
}