# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: |
          git config --global user.email "kay.paetzold@mail.com"
          git config --global user.name "Kay Paetzold"
          npm install
          npm run build
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          folder: build
          branch: gh-pages 
